Repository vas3k/vas3k.club, pull requests merged in 2020-10, with the labels that each got.

#406 Fix #402: Upvote button issue on mobile
  frontend/static/css/components.css
Labels: bug, hacktoberfest

#403 issue #397: fix weekly digest intros html escaping
  frontend/html/emails/daily.html
  frontend/html/emails/weekly.html
Labels: ¯\_(ツ)_/¯

#411 Fix shrug label link in README
  README.md
Labels: hacktoberfest

#427 Отображать ошибку, если падает запрос на загрузку media к комментарию
  frontend/static/js/inline-attachment.js
Labels: hacktoberfest
